### ISSUE TITLE
Feature :: Job Tracker v1

### ISSUE THREAD

**Issue by horaciovelvetine** [horaciovelvetine/horaciovelvetine#26]
The job tracker application should at least be up and minimally working, if not particularly visually pleasing. 

TODOs:

- [ ] Index page where all open job opportunities are displayed according to the stage of the process they are in (extended include a different means of sorting this view, by context job-todos)
- [ ] show page (maybe popover like in app screenshots) shows an opportunities details including notes and todos and contacts etc and allows editing, adding, removing, deleting and changing in the object in a variety of CRUD ways. 
- [ ] A modular Resume object which is associated with each company/opportunity which pulls from self info and allows a custom tailored resume with a personalized link to apply with
